name: Metrics Deck

on:
  schedule:
    - cron: "25 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  metrics-base:
    if: ${{ secrets.METRICS_TOKEN != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate base metrics card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: katakarn
          filename: assets/metrics-base.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Bangkok
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_lines: yes

  metrics-wakatime:
    if: ${{ secrets.METRICS_TOKEN != '' && secrets.WAKATIME_API_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate wakatime metrics card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: katakarn
          filename: assets/metrics-wakatime.svg
          template: classic
          base: ""
          config_timezone: Asia/Bangkok
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_days: 7
          plugin_wakatime_sections: time, projects, editors, languages, os
